[project]
name = "airsim-simulation"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "opencv-python",
    "pymavlink",
]

[dependency-groups]
dev = []

[tool.pytest.ini_options]
addopts = "-p no:launch_pytest -p no:launch_testing -p no:launch_ros -p no:ament_xmllint -p no:ament_copyright -p no:ament_black -p no:ament_mypy -p no:ament_flake8 -p no:ament_lint -p no:ament_pep257"
